CC=gcc 
CFLAGS=-Wall

INC=-I./

queue_test: queue.o queue_test.o

bits: bits.o

divisor: divisor.o

double_list: double_list.o

single_list: single_list.o

tree: tree.o

numbers: numbers.o

pointers: pointers.o

stack_test: stack.o stack_test.o

clean:
	rm -f *.o queue_test bits double_list single_list divisor pointers numbers tree stack_test
