CC=gcc
CFLAGS=-Wall

INC=-I./

queue_test: queue.o queue_test.o

bits: bits.o

divisor: divisor.o

double_list: double_list.o

list_test: single_list.o list_test.o sort.o

tree: tree.o

numbers: numbers.o

pointers: pointers.o

stack_test: stack.o stack_test.o

array_test: arrays.o array_test.o sort.o

clean:
	rm -f *.o queue_test bits double_list list_test divisor pointers numbers tree stack_test array_test
